// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/quantex.proto

package GrpcQuantex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuantexService_UpdateOrder_FullMethodName    = "/GrpcQuantex.QuantexService/UpdateOrder"
	QuantexService_ReloadStrategy_FullMethodName = "/GrpcQuantex.QuantexService/ReloadStrategy"
)

// QuantexServiceClient is the client API for QuantexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuantexServiceClient interface {
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReloadStrategy(ctx context.Context, in *ReloadStrategyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type quantexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantexServiceClient(cc grpc.ClientConnInterface) QuantexServiceClient {
	return &quantexServiceClient{cc}
}

func (c *quantexServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuantexService_UpdateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantexServiceClient) ReloadStrategy(ctx context.Context, in *ReloadStrategyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuantexService_ReloadStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuantexServiceServer is the server API for QuantexService service.
// All implementations must embed UnimplementedQuantexServiceServer
// for forward compatibility.
type QuantexServiceServer interface {
	UpdateOrder(context.Context, *UpdateOrderRequest) (*emptypb.Empty, error)
	ReloadStrategy(context.Context, *ReloadStrategyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedQuantexServiceServer()
}

// UnimplementedQuantexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuantexServiceServer struct{}

func (UnimplementedQuantexServiceServer) UpdateOrder(context.Context, *UpdateOrderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedQuantexServiceServer) ReloadStrategy(context.Context, *ReloadStrategyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadStrategy not implemented")
}
func (UnimplementedQuantexServiceServer) mustEmbedUnimplementedQuantexServiceServer() {}
func (UnimplementedQuantexServiceServer) testEmbeddedByValue()                        {}

// UnsafeQuantexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantexServiceServer will
// result in compilation errors.
type UnsafeQuantexServiceServer interface {
	mustEmbedUnimplementedQuantexServiceServer()
}

func RegisterQuantexServiceServer(s grpc.ServiceRegistrar, srv QuantexServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuantexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuantexService_ServiceDesc, srv)
}

func _QuantexService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantexServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantexService_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantexServiceServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantexService_ReloadStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantexServiceServer).ReloadStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantexService_ReloadStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantexServiceServer).ReloadStrategy(ctx, req.(*ReloadStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuantexService_ServiceDesc is the grpc.ServiceDesc for QuantexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuantexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcQuantex.QuantexService",
	HandlerType: (*QuantexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateOrder",
			Handler:    _QuantexService_UpdateOrder_Handler,
		},
		{
			MethodName: "ReloadStrategy",
			Handler:    _QuantexService_ReloadStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quantex.proto",
}
