// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/quantex.proto

package GrpcQuantex

import (
	order "github.com/coda247/orbit/Grpc/order"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *order.Order           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_proto_quantex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_quantex_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateOrderRequest) GetOrder() *order.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ReloadStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadStrategyRequest) Reset() {
	*x = ReloadStrategyRequest{}
	mi := &file_proto_quantex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadStrategyRequest) ProtoMessage() {}

func (x *ReloadStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quantex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadStrategyRequest.ProtoReflect.Descriptor instead.
func (*ReloadStrategyRequest) Descriptor() ([]byte, []int) {
	return file_proto_quantex_proto_rawDescGZIP(), []int{1}
}

func (x *ReloadStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

var File_proto_quantex_proto protoreflect.FileDescriptor

const file_proto_quantex_proto_rawDesc = "" +
	"\n" +
	"\x13proto/quantex.proto\x12\vGrpcQuantex\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11proto/order.proto\"<\n" +
	"\x12UpdateOrderRequest\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.GrpcOrder.OrderR\x05order\"8\n" +
	"\x15ReloadStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId2\xaa\x01\n" +
	"\x0eQuantexService\x12H\n" +
	"\vUpdateOrder\x12\x1f.GrpcQuantex.UpdateOrderRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x0eReloadStrategy\x12\".GrpcQuantex.ReloadStrategyRequest\x1a\x16.google.protobuf.Empty\"\x00B3Z1github.com/coda247/orbit/Grpc/quantex;GrpcQuantexb\x06proto3"

var (
	file_proto_quantex_proto_rawDescOnce sync.Once
	file_proto_quantex_proto_rawDescData []byte
)

func file_proto_quantex_proto_rawDescGZIP() []byte {
	file_proto_quantex_proto_rawDescOnce.Do(func() {
		file_proto_quantex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quantex_proto_rawDesc), len(file_proto_quantex_proto_rawDesc)))
	})
	return file_proto_quantex_proto_rawDescData
}

var file_proto_quantex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_quantex_proto_goTypes = []any{
	(*UpdateOrderRequest)(nil),    // 0: GrpcQuantex.UpdateOrderRequest
	(*ReloadStrategyRequest)(nil), // 1: GrpcQuantex.ReloadStrategyRequest
	(*order.Order)(nil),           // 2: GrpcOrder.Order
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_proto_quantex_proto_depIdxs = []int32{
	2, // 0: GrpcQuantex.UpdateOrderRequest.order:type_name -> GrpcOrder.Order
	0, // 1: GrpcQuantex.QuantexService.UpdateOrder:input_type -> GrpcQuantex.UpdateOrderRequest
	1, // 2: GrpcQuantex.QuantexService.ReloadStrategy:input_type -> GrpcQuantex.ReloadStrategyRequest
	3, // 3: GrpcQuantex.QuantexService.UpdateOrder:output_type -> google.protobuf.Empty
	3, // 4: GrpcQuantex.QuantexService.ReloadStrategy:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_quantex_proto_init() }
func file_proto_quantex_proto_init() {
	if File_proto_quantex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quantex_proto_rawDesc), len(file_proto_quantex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quantex_proto_goTypes,
		DependencyIndexes: file_proto_quantex_proto_depIdxs,
		MessageInfos:      file_proto_quantex_proto_msgTypes,
	}.Build()
	File_proto_quantex_proto = out.File
	file_proto_quantex_proto_goTypes = nil
	file_proto_quantex_proto_depIdxs = nil
}
