// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/engine.proto

package GrpcEngine

import (
	order "github.com/coda247/orbit/Grpc/order"
	symbol "github.com/coda247/orbit/Grpc/symbol"
	utils "github.com/coda247/orbit/Grpc/utils"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderKey      *order.OrderKey        `protobuf:"bytes,1,opt,name=order_key,json=orderKey,proto3" json:"order_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOrderRequest) Reset() {
	*x = FetchOrderRequest{}
	mi := &file_proto_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrderRequest) ProtoMessage() {}

func (x *FetchOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrderRequest.ProtoReflect.Descriptor instead.
func (*FetchOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{0}
}

func (x *FetchOrderRequest) GetOrderKey() *order.OrderKey {
	if x != nil {
		return x.OrderKey
	}
	return nil
}

type FetchOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *order.Order           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOrderResponse) Reset() {
	*x = FetchOrderResponse{}
	mi := &file_proto_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrderResponse) ProtoMessage() {}

func (x *FetchOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrderResponse.ProtoReflect.Descriptor instead.
func (*FetchOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{1}
}

func (x *FetchOrderResponse) GetOrder() *order.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type FetchOpenOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *symbol.Symbol         `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOpenOrdersRequest) Reset() {
	*x = FetchOpenOrdersRequest{}
	mi := &file_proto_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOpenOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOpenOrdersRequest) ProtoMessage() {}

func (x *FetchOpenOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOpenOrdersRequest.ProtoReflect.Descriptor instead.
func (*FetchOpenOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{2}
}

func (x *FetchOpenOrdersRequest) GetSymbol() *symbol.Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *FetchOpenOrdersRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

type BookOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceQuantity []*utils.Decimal       `protobuf:"bytes,1,rep,name=price_quantity,json=priceQuantity,proto3" json:"price_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookOrder) Reset() {
	*x = BookOrder{}
	mi := &file_proto_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookOrder) ProtoMessage() {}

func (x *BookOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookOrder.ProtoReflect.Descriptor instead.
func (*BookOrder) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{3}
}

func (x *BookOrder) GetPriceQuantity() []*utils.Decimal {
	if x != nil {
		return x.PriceQuantity
	}
	return nil
}

type FetchOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *symbol.Symbol         `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOrderBookRequest) Reset() {
	*x = FetchOrderBookRequest{}
	mi := &file_proto_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrderBookRequest) ProtoMessage() {}

func (x *FetchOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrderBookRequest.ProtoReflect.Descriptor instead.
func (*FetchOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{4}
}

func (x *FetchOrderBookRequest) GetSymbol() *symbol.Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *FetchOrderBookRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FetchOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *symbol.Symbol         `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids          []*BookOrder           `protobuf:"bytes,2,rep,name=Bids,proto3" json:"Bids,omitempty"`
	Asks          []*BookOrder           `protobuf:"bytes,3,rep,name=Asks,proto3" json:"Asks,omitempty"`
	Sequence      int64                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOrderBookResponse) Reset() {
	*x = FetchOrderBookResponse{}
	mi := &file_proto_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrderBookResponse) ProtoMessage() {}

func (x *FetchOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrderBookResponse.ProtoReflect.Descriptor instead.
func (*FetchOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{5}
}

func (x *FetchOrderBookResponse) GetSymbol() *symbol.Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *FetchOrderBookResponse) GetBids() []*BookOrder {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *FetchOrderBookResponse) GetAsks() []*BookOrder {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *FetchOrderBookResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type CalcMarketOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *symbol.Symbol         `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Quantity      *utils.Decimal         `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Volume        *utils.Decimal         `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcMarketOrderRequest) Reset() {
	*x = CalcMarketOrderRequest{}
	mi := &file_proto_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcMarketOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcMarketOrderRequest) ProtoMessage() {}

func (x *CalcMarketOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcMarketOrderRequest.ProtoReflect.Descriptor instead.
func (*CalcMarketOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{6}
}

func (x *CalcMarketOrderRequest) GetSymbol() *symbol.Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *CalcMarketOrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *CalcMarketOrderRequest) GetQuantity() *utils.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *CalcMarketOrderRequest) GetVolume() *utils.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

type CalcMarketOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      *utils.Decimal         `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Locked        *utils.Decimal         `protobuf:"bytes,2,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcMarketOrderResponse) Reset() {
	*x = CalcMarketOrderResponse{}
	mi := &file_proto_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcMarketOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcMarketOrderResponse) ProtoMessage() {}

func (x *CalcMarketOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcMarketOrderResponse.ProtoReflect.Descriptor instead.
func (*CalcMarketOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{7}
}

func (x *CalcMarketOrderResponse) GetQuantity() *utils.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *CalcMarketOrderResponse) GetLocked() *utils.Decimal {
	if x != nil {
		return x.Locked
	}
	return nil
}

type FetchMarketPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *symbol.Symbol         `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMarketPriceRequest) Reset() {
	*x = FetchMarketPriceRequest{}
	mi := &file_proto_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMarketPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMarketPriceRequest) ProtoMessage() {}

func (x *FetchMarketPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMarketPriceRequest.ProtoReflect.Descriptor instead.
func (*FetchMarketPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{8}
}

func (x *FetchMarketPriceRequest) GetSymbol() *symbol.Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

type FetchMarketPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *utils.Decimal         `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMarketPriceResponse) Reset() {
	*x = FetchMarketPriceResponse{}
	mi := &file_proto_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMarketPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMarketPriceResponse) ProtoMessage() {}

func (x *FetchMarketPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMarketPriceResponse.ProtoReflect.Descriptor instead.
func (*FetchMarketPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{9}
}

func (x *FetchMarketPriceResponse) GetPrice() *utils.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

var File_proto_engine_proto protoreflect.FileDescriptor

const file_proto_engine_proto_rawDesc = "" +
	"\n" +
	"\x12proto/engine.proto\x12\n" +
	"GrpcEngine\x1a\x11proto/utils.proto\x1a\x11proto/order.proto\x1a\x12proto/symbol.proto\"E\n" +
	"\x11FetchOrderRequest\x120\n" +
	"\torder_key\x18\x01 \x01(\v2\x13.GrpcOrder.OrderKeyR\borderKey\"<\n" +
	"\x12FetchOrderResponse\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.GrpcOrder.OrderR\x05order\"X\n" +
	"\x16FetchOpenOrdersRequest\x12*\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.GrpcSymbol.SymbolR\x06symbol\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\"F\n" +
	"\tBookOrder\x129\n" +
	"\x0eprice_quantity\x18\x01 \x03(\v2\x12.GrpcUtils.DecimalR\rpriceQuantity\"Y\n" +
	"\x15FetchOrderBookRequest\x12*\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.GrpcSymbol.SymbolR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"\xb6\x01\n" +
	"\x16FetchOrderBookResponse\x12*\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.GrpcSymbol.SymbolR\x06symbol\x12)\n" +
	"\x04Bids\x18\x02 \x03(\v2\x15.GrpcEngine.BookOrderR\x04Bids\x12)\n" +
	"\x04Asks\x18\x03 \x03(\v2\x15.GrpcEngine.BookOrderR\x04Asks\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\"\xb4\x01\n" +
	"\x16CalcMarketOrderRequest\x12*\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.GrpcSymbol.SymbolR\x06symbol\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12.\n" +
	"\bquantity\x18\x03 \x01(\v2\x12.GrpcUtils.DecimalR\bquantity\x12*\n" +
	"\x06volume\x18\x04 \x01(\v2\x12.GrpcUtils.DecimalR\x06volume\"u\n" +
	"\x17CalcMarketOrderResponse\x12.\n" +
	"\bquantity\x18\x01 \x01(\v2\x12.GrpcUtils.DecimalR\bquantity\x12*\n" +
	"\x06locked\x18\x02 \x01(\v2\x12.GrpcUtils.DecimalR\x06locked\"E\n" +
	"\x17FetchMarketPriceRequest\x12*\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.GrpcSymbol.SymbolR\x06symbol\"D\n" +
	"\x18FetchMarketPriceResponse\x12(\n" +
	"\x05price\x18\x01 \x01(\v2\x12.GrpcUtils.DecimalR\x05price2\x80\x03\n" +
	"\x15MatchingEngineService\x12M\n" +
	"\n" +
	"FetchOrder\x12\x1d.GrpcEngine.FetchOrderRequest\x1a\x1e.GrpcEngine.FetchOrderResponse\"\x00\x12Y\n" +
	"\x0eFetchOrderBook\x12!.GrpcEngine.FetchOrderBookRequest\x1a\".GrpcEngine.FetchOrderBookResponse\"\x00\x12\\\n" +
	"\x0fCalcMarketOrder\x12\".GrpcEngine.CalcMarketOrderRequest\x1a#.GrpcEngine.CalcMarketOrderResponse\"\x00\x12_\n" +
	"\x10FetchMarketPrice\x12#.GrpcEngine.FetchMarketPriceRequest\x1a$.GrpcEngine.FetchMarketPriceResponse\"\x00B1Z/github.com/coda247/orbit/Grpc/engine;GrpcEngineb\x06proto3"

var (
	file_proto_engine_proto_rawDescOnce sync.Once
	file_proto_engine_proto_rawDescData []byte
)

func file_proto_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)))
	})
	return file_proto_engine_proto_rawDescData
}

var file_proto_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_engine_proto_goTypes = []any{
	(*FetchOrderRequest)(nil),        // 0: GrpcEngine.FetchOrderRequest
	(*FetchOrderResponse)(nil),       // 1: GrpcEngine.FetchOrderResponse
	(*FetchOpenOrdersRequest)(nil),   // 2: GrpcEngine.FetchOpenOrdersRequest
	(*BookOrder)(nil),                // 3: GrpcEngine.BookOrder
	(*FetchOrderBookRequest)(nil),    // 4: GrpcEngine.FetchOrderBookRequest
	(*FetchOrderBookResponse)(nil),   // 5: GrpcEngine.FetchOrderBookResponse
	(*CalcMarketOrderRequest)(nil),   // 6: GrpcEngine.CalcMarketOrderRequest
	(*CalcMarketOrderResponse)(nil),  // 7: GrpcEngine.CalcMarketOrderResponse
	(*FetchMarketPriceRequest)(nil),  // 8: GrpcEngine.FetchMarketPriceRequest
	(*FetchMarketPriceResponse)(nil), // 9: GrpcEngine.FetchMarketPriceResponse
	(*order.OrderKey)(nil),           // 10: GrpcOrder.OrderKey
	(*order.Order)(nil),              // 11: GrpcOrder.Order
	(*symbol.Symbol)(nil),            // 12: GrpcSymbol.Symbol
	(*utils.Decimal)(nil),            // 13: GrpcUtils.Decimal
}
var file_proto_engine_proto_depIdxs = []int32{
	10, // 0: GrpcEngine.FetchOrderRequest.order_key:type_name -> GrpcOrder.OrderKey
	11, // 1: GrpcEngine.FetchOrderResponse.order:type_name -> GrpcOrder.Order
	12, // 2: GrpcEngine.FetchOpenOrdersRequest.symbol:type_name -> GrpcSymbol.Symbol
	13, // 3: GrpcEngine.BookOrder.price_quantity:type_name -> GrpcUtils.Decimal
	12, // 4: GrpcEngine.FetchOrderBookRequest.symbol:type_name -> GrpcSymbol.Symbol
	12, // 5: GrpcEngine.FetchOrderBookResponse.symbol:type_name -> GrpcSymbol.Symbol
	3,  // 6: GrpcEngine.FetchOrderBookResponse.Bids:type_name -> GrpcEngine.BookOrder
	3,  // 7: GrpcEngine.FetchOrderBookResponse.Asks:type_name -> GrpcEngine.BookOrder
	12, // 8: GrpcEngine.CalcMarketOrderRequest.symbol:type_name -> GrpcSymbol.Symbol
	13, // 9: GrpcEngine.CalcMarketOrderRequest.quantity:type_name -> GrpcUtils.Decimal
	13, // 10: GrpcEngine.CalcMarketOrderRequest.volume:type_name -> GrpcUtils.Decimal
	13, // 11: GrpcEngine.CalcMarketOrderResponse.quantity:type_name -> GrpcUtils.Decimal
	13, // 12: GrpcEngine.CalcMarketOrderResponse.locked:type_name -> GrpcUtils.Decimal
	12, // 13: GrpcEngine.FetchMarketPriceRequest.symbol:type_name -> GrpcSymbol.Symbol
	13, // 14: GrpcEngine.FetchMarketPriceResponse.price:type_name -> GrpcUtils.Decimal
	0,  // 15: GrpcEngine.MatchingEngineService.FetchOrder:input_type -> GrpcEngine.FetchOrderRequest
	4,  // 16: GrpcEngine.MatchingEngineService.FetchOrderBook:input_type -> GrpcEngine.FetchOrderBookRequest
	6,  // 17: GrpcEngine.MatchingEngineService.CalcMarketOrder:input_type -> GrpcEngine.CalcMarketOrderRequest
	8,  // 18: GrpcEngine.MatchingEngineService.FetchMarketPrice:input_type -> GrpcEngine.FetchMarketPriceRequest
	1,  // 19: GrpcEngine.MatchingEngineService.FetchOrder:output_type -> GrpcEngine.FetchOrderResponse
	5,  // 20: GrpcEngine.MatchingEngineService.FetchOrderBook:output_type -> GrpcEngine.FetchOrderBookResponse
	7,  // 21: GrpcEngine.MatchingEngineService.CalcMarketOrder:output_type -> GrpcEngine.CalcMarketOrderResponse
	9,  // 22: GrpcEngine.MatchingEngineService.FetchMarketPrice:output_type -> GrpcEngine.FetchMarketPriceResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_engine_proto_init() }
func file_proto_engine_proto_init() {
	if File_proto_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_proto_depIdxs,
		MessageInfos:      file_proto_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_proto = out.File
	file_proto_engine_proto_goTypes = nil
	file_proto_engine_proto_depIdxs = nil
}
