// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/engine.proto

package GrpcEngine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingEngineService_FetchOrder_FullMethodName       = "/GrpcEngine.MatchingEngineService/FetchOrder"
	MatchingEngineService_FetchOrderBook_FullMethodName   = "/GrpcEngine.MatchingEngineService/FetchOrderBook"
	MatchingEngineService_CalcMarketOrder_FullMethodName  = "/GrpcEngine.MatchingEngineService/CalcMarketOrder"
	MatchingEngineService_FetchMarketPrice_FullMethodName = "/GrpcEngine.MatchingEngineService/FetchMarketPrice"
)

// MatchingEngineServiceClient is the client API for MatchingEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchingEngineServiceClient interface {
	FetchOrder(ctx context.Context, in *FetchOrderRequest, opts ...grpc.CallOption) (*FetchOrderResponse, error)
	FetchOrderBook(ctx context.Context, in *FetchOrderBookRequest, opts ...grpc.CallOption) (*FetchOrderBookResponse, error)
	CalcMarketOrder(ctx context.Context, in *CalcMarketOrderRequest, opts ...grpc.CallOption) (*CalcMarketOrderResponse, error)
	FetchMarketPrice(ctx context.Context, in *FetchMarketPriceRequest, opts ...grpc.CallOption) (*FetchMarketPriceResponse, error)
}

type matchingEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingEngineServiceClient(cc grpc.ClientConnInterface) MatchingEngineServiceClient {
	return &matchingEngineServiceClient{cc}
}

func (c *matchingEngineServiceClient) FetchOrder(ctx context.Context, in *FetchOrderRequest, opts ...grpc.CallOption) (*FetchOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchOrderResponse)
	err := c.cc.Invoke(ctx, MatchingEngineService_FetchOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineServiceClient) FetchOrderBook(ctx context.Context, in *FetchOrderBookRequest, opts ...grpc.CallOption) (*FetchOrderBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchOrderBookResponse)
	err := c.cc.Invoke(ctx, MatchingEngineService_FetchOrderBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineServiceClient) CalcMarketOrder(ctx context.Context, in *CalcMarketOrderRequest, opts ...grpc.CallOption) (*CalcMarketOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalcMarketOrderResponse)
	err := c.cc.Invoke(ctx, MatchingEngineService_CalcMarketOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineServiceClient) FetchMarketPrice(ctx context.Context, in *FetchMarketPriceRequest, opts ...grpc.CallOption) (*FetchMarketPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchMarketPriceResponse)
	err := c.cc.Invoke(ctx, MatchingEngineService_FetchMarketPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingEngineServiceServer is the server API for MatchingEngineService service.
// All implementations must embed UnimplementedMatchingEngineServiceServer
// for forward compatibility.
type MatchingEngineServiceServer interface {
	FetchOrder(context.Context, *FetchOrderRequest) (*FetchOrderResponse, error)
	FetchOrderBook(context.Context, *FetchOrderBookRequest) (*FetchOrderBookResponse, error)
	CalcMarketOrder(context.Context, *CalcMarketOrderRequest) (*CalcMarketOrderResponse, error)
	FetchMarketPrice(context.Context, *FetchMarketPriceRequest) (*FetchMarketPriceResponse, error)
	mustEmbedUnimplementedMatchingEngineServiceServer()
}

// UnimplementedMatchingEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingEngineServiceServer struct{}

func (UnimplementedMatchingEngineServiceServer) FetchOrder(context.Context, *FetchOrderRequest) (*FetchOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOrder not implemented")
}
func (UnimplementedMatchingEngineServiceServer) FetchOrderBook(context.Context, *FetchOrderBookRequest) (*FetchOrderBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOrderBook not implemented")
}
func (UnimplementedMatchingEngineServiceServer) CalcMarketOrder(context.Context, *CalcMarketOrderRequest) (*CalcMarketOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcMarketOrder not implemented")
}
func (UnimplementedMatchingEngineServiceServer) FetchMarketPrice(context.Context, *FetchMarketPriceRequest) (*FetchMarketPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMarketPrice not implemented")
}
func (UnimplementedMatchingEngineServiceServer) mustEmbedUnimplementedMatchingEngineServiceServer() {}
func (UnimplementedMatchingEngineServiceServer) testEmbeddedByValue()                               {}

// UnsafeMatchingEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingEngineServiceServer will
// result in compilation errors.
type UnsafeMatchingEngineServiceServer interface {
	mustEmbedUnimplementedMatchingEngineServiceServer()
}

func RegisterMatchingEngineServiceServer(s grpc.ServiceRegistrar, srv MatchingEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchingEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingEngineService_ServiceDesc, srv)
}

func _MatchingEngineService_FetchOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).FetchOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_FetchOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).FetchOrder(ctx, req.(*FetchOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngineService_FetchOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).FetchOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_FetchOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).FetchOrderBook(ctx, req.(*FetchOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngineService_CalcMarketOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcMarketOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).CalcMarketOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_CalcMarketOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).CalcMarketOrder(ctx, req.(*CalcMarketOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngineService_FetchMarketPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMarketPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).FetchMarketPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_FetchMarketPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).FetchMarketPrice(ctx, req.(*FetchMarketPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingEngineService_ServiceDesc is the grpc.ServiceDesc for MatchingEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcEngine.MatchingEngineService",
	HandlerType: (*MatchingEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchOrder",
			Handler:    _MatchingEngineService_FetchOrder_Handler,
		},
		{
			MethodName: "FetchOrderBook",
			Handler:    _MatchingEngineService_FetchOrderBook_Handler,
		},
		{
			MethodName: "CalcMarketOrder",
			Handler:    _MatchingEngineService_CalcMarketOrder_Handler,
		},
		{
			MethodName: "FetchMarketPrice",
			Handler:    _MatchingEngineService_FetchMarketPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/engine.proto",
}
