// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/order.proto

package GrpcOrder

import (
	symbol "github.com/coda247/orbit/Grpc/symbol"
	utils "github.com/coda247/orbit/Grpc/utils"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        *symbol.Symbol         `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Uuid          []byte                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Price         *utils.Decimal         `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	StopPrice     *utils.Decimal         `protobuf:"bytes,6,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	Fake          bool                   `protobuf:"varint,7,opt,name=fake,proto3" json:"fake,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderKey) Reset() {
	*x = OrderKey{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderKey) ProtoMessage() {}

func (x *OrderKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderKey.ProtoReflect.Descriptor instead.
func (*OrderKey) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderKey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderKey) GetSymbol() *symbol.Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *OrderKey) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderKey) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *OrderKey) GetPrice() *utils.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderKey) GetStopPrice() *utils.Decimal {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *OrderKey) GetFake() bool {
	if x != nil {
		return x.Fake
	}
	return false
}

func (x *OrderKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid           []byte                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MemberId       int64                  `protobuf:"varint,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Symbol         *symbol.Symbol         `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side           string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Price          *utils.Decimal         `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	StopPrice      *utils.Decimal         `protobuf:"bytes,8,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	Quantity       *utils.Decimal         `protobuf:"bytes,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	FilledQuantity *utils.Decimal         `protobuf:"bytes,10,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	Fake           bool                   `protobuf:"varint,11,opt,name=fake,proto3" json:"fake,omitempty"`
	Cancelled      bool                   `protobuf:"varint,12,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Order) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *Order) GetSymbol() *symbol.Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *Order) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Order) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Order) GetPrice() *utils.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Order) GetStopPrice() *utils.Decimal {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *Order) GetQuantity() *utils.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Order) GetFilledQuantity() *utils.Decimal {
	if x != nil {
		return x.FilledQuantity
	}
	return nil
}

func (x *Order) GetFake() bool {
	if x != nil {
		return x.Fake
	}
	return false
}

func (x *Order) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\tGrpcOrder\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11proto/utils.proto\x1a\x12proto/symbol.proto\"\x9a\x02\n" +
	"\bOrderKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x06symbol\x18\x02 \x01(\v2\x12.GrpcSymbol.SymbolR\x06symbol\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\fR\x04uuid\x12(\n" +
	"\x05price\x18\x05 \x01(\v2\x12.GrpcUtils.DecimalR\x05price\x121\n" +
	"\n" +
	"stop_price\x18\x06 \x01(\v2\x12.GrpcUtils.DecimalR\tstopPrice\x12\x12\n" +
	"\x04fake\x18\a \x01(\bR\x04fake\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd3\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\fR\x04uuid\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\x03R\bmemberId\x12*\n" +
	"\x06symbol\x18\x04 \x01(\v2\x12.GrpcSymbol.SymbolR\x06symbol\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12(\n" +
	"\x05price\x18\a \x01(\v2\x12.GrpcUtils.DecimalR\x05price\x121\n" +
	"\n" +
	"stop_price\x18\b \x01(\v2\x12.GrpcUtils.DecimalR\tstopPrice\x12.\n" +
	"\bquantity\x18\t \x01(\v2\x12.GrpcUtils.DecimalR\bquantity\x12;\n" +
	"\x0ffilled_quantity\x18\n" +
	" \x01(\v2\x12.GrpcUtils.DecimalR\x0efilledQuantity\x12\x12\n" +
	"\x04fake\x18\v \x01(\bR\x04fake\x12\x1c\n" +
	"\tcancelled\x18\f \x01(\bR\tcancelled\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB/Z-github.com/coda247/orbit/Grpc/order;GrpcOrderb\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_order_proto_goTypes = []any{
	(*OrderKey)(nil),              // 0: GrpcOrder.OrderKey
	(*Order)(nil),                 // 1: GrpcOrder.Order
	(*symbol.Symbol)(nil),         // 2: GrpcSymbol.Symbol
	(*utils.Decimal)(nil),         // 3: GrpcUtils.Decimal
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_order_proto_depIdxs = []int32{
	2,  // 0: GrpcOrder.OrderKey.symbol:type_name -> GrpcSymbol.Symbol
	3,  // 1: GrpcOrder.OrderKey.price:type_name -> GrpcUtils.Decimal
	3,  // 2: GrpcOrder.OrderKey.stop_price:type_name -> GrpcUtils.Decimal
	4,  // 3: GrpcOrder.OrderKey.created_at:type_name -> google.protobuf.Timestamp
	2,  // 4: GrpcOrder.Order.symbol:type_name -> GrpcSymbol.Symbol
	3,  // 5: GrpcOrder.Order.price:type_name -> GrpcUtils.Decimal
	3,  // 6: GrpcOrder.Order.stop_price:type_name -> GrpcUtils.Decimal
	3,  // 7: GrpcOrder.Order.quantity:type_name -> GrpcUtils.Decimal
	3,  // 8: GrpcOrder.Order.filled_quantity:type_name -> GrpcUtils.Decimal
	4,  // 9: GrpcOrder.Order.created_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
