// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: utils.proto

package GrpcUtils

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=Val,proto3" json:"Val,omitempty"`
	Exp           int32                  `protobuf:"varint,2,opt,name=Exp,proto3" json:"Exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_utils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_utils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_utils_proto_rawDescGZIP(), []int{0}
}

func (x *Decimal) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *Decimal) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_utils_proto protoreflect.FileDescriptor

const file_utils_proto_rawDesc = "" +
	"\n" +
	"\vutils.proto\x12\tGrpcUtils\"-\n" +
	"\aDecimal\x12\x10\n" +
	"\x03Val\x18\x01 \x01(\x03R\x03Val\x12\x10\n" +
	"\x03Exp\x18\x02 \x01(\x05R\x03ExpB/Z-github.com/coda247/orbit/Grpc/utils;GrpcUtilsb\x06proto3"

var (
	file_utils_proto_rawDescOnce sync.Once
	file_utils_proto_rawDescData []byte
)

func file_utils_proto_rawDescGZIP() []byte {
	file_utils_proto_rawDescOnce.Do(func() {
		file_utils_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utils_proto_rawDesc), len(file_utils_proto_rawDesc)))
	})
	return file_utils_proto_rawDescData
}

var file_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_utils_proto_goTypes = []any{
	(*Decimal)(nil), // 0: GrpcUtils.Decimal
}
var file_utils_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_proto_init() }
func file_utils_proto_init() {
	if File_utils_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utils_proto_rawDesc), len(file_utils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utils_proto_goTypes,
		DependencyIndexes: file_utils_proto_depIdxs,
		MessageInfos:      file_utils_proto_msgTypes,
	}.Build()
	File_utils_proto = out.File
	file_utils_proto_goTypes = nil
	file_utils_proto_depIdxs = nil
}
